// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		//int n = Integer.parseInt(args[0]);
		int n = 100000;

		double lowerThanHalf = 0;
		double higherThanHalf = 0;
		while (n!=0)
		{
			double rand = Math.random();
			if (rand <0.5)
			{lowerThanHalf++;}
			else 
			{higherThanHalf++;}
			n--;
		}

		double ratio = lowerThanHalf/higherThanHalf;
		if (ratio > 1)
		{ratio = higherThanHalf/lowerThanHalf;}
		System.out.println(">0.5: " + higherThanHalf);
		System.out.println("<0.5: " + lowerThanHalf);
		if (ratio > 0)
		{System.out.println("Ratio: " + ratio);}


	}
}
